// generated by Neptune Namespaces v4.x.x
// file: ArtSuite.Test.Assert/index.js

(module.exports = require('./namespace'))
.includeInNamespace(require('./Assert'))
.addModules({
  CommunicationStatus: require('./CommunicationStatus'),
  Comparison:          require('./Comparison'),
  Lib:                 require('./Lib'),
  Presentation:        require('./Presentation'),
  Promises:            require('./Promises'),
  StandardImport:      require('./StandardImport'),
  Truth:               require('./Truth'),
  Type:                require('./Type')
});