// generated by Neptune Namespaces v4.x.x
// file: ArtSuite.Test.Assert/namespace.js

module.exports = require('neptune-namespaces-runtime').addNamespace(
  'ArtSuite.Test.Assert',
  (class Assert extends Neptune.PackageNamespace {})
  ._configureNamespace(require('../../package.json'))
);
