// generated by Neptune Namespaces v4.x.x
// file: Jest/index.js

(module.exports = require('./namespace'))

.addModules({
  CreateObjectTreeFactoryTest: require('./CreateObjectTreeFactory.test'),
  ReadmeTest:                  require('./README.test'),
  RefressionsTest:             require('./Refressions.test'),
  StandardImport:              require('./StandardImport'),
  UsingFactories:              require('./UsingFactories'),
  UsingFactoriesTest:          require('./UsingFactories.test')
});