# generated by Neptune Namespaces v0.5.0
# file: Runtime/namespace.coffee

Neptune = require 'neptune-namespaces'
module.exports = Neptune.Runtime ||
Neptune.addNamespace 'Runtime', class Runtime extends Neptune.Base
  ;