// generated by Neptune Namespaces v4.x.x
// file: NeptuneNamespaces/Generators/index.js

(module.exports = require('./namespace'))

.addModules({
  IndexJsGenerator:     require('./IndexJsGenerator'),
  NamespaceJsGenerator: require('./NamespaceJsGenerator')
});