# generated by Neptune Namespaces v3.x.x
# file: NeptuneNamespaces/Generators/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  IndexGenerator:     require './IndexGenerator'    
  NamespaceGenerator: require './NamespaceGenerator'