// generated by Neptune Namespaces v3.x.x
// file: NeptuneNamespaces/Generators/index.js

(module.exports = require('./namespace'))

.addModules({
  IndexGenerator:       require('./IndexGenerator'),
  IndexJsGenerator:     require('./IndexJsGenerator'),
  NamespaceGenerator:   require('./NamespaceGenerator'),
  NamespaceJsGenerator: require('./NamespaceJsGenerator')
});