// generated by Neptune Namespaces v4.x.x
// file: NeptuneNamespaces/Generators/namespace.js

module.exports = require('../namespace').addNamespace(
  'Generators',
  class Generators extends Neptune.PackageNamespace {}
);
