# generated by Neptune Namespaces v3.x.x
# file: Art.StandardLib/Inspect/index.coffee

module.exports = require './namespace'
module.exports
.includeInNamespace require './Inspect'
.addModules
  FormattedInspect:       require './FormattedInspect'      
  InspectedObjectLiteral: require './InspectedObjectLiteral'
  InspectedObjects:       require './InspectedObjects'      
  Inspector:              require './Inspector'             
  Inspector2:             require './Inspector2'            
  PlainObjects:           require './PlainObjects'          
require './Inspected'