# generated by Neptune Namespaces v3.x.x
# file: Art.StandardLib/Inspect/namespace.coffee

module.exports = (require '../namespace').addNamespace('Inspect', class Inspect extends Neptune.PackageNamespace)
require './Inspected/namespace'