// generated by Neptune Namespaces v4.x.x
// file: Art/HtmlFactory/index.js

(module.exports = require('./namespace'))
.includeInNamespace(require('./HtmlFactory'))
.addModules({
  HtmlElementNames: require('./HtmlElementNames'),
  HtmlTextNode:     require('./HtmlTextNode')
});