# generated by Neptune Namespaces v3.x.x
# file: Art/HtmlFactory/index.coffee

module.exports = require './namespace'
module.exports
.includeInNamespace require './HtmlFactory'
.addModules
  HtmlElementNames: require './HtmlElementNames'
  HtmlTextNode:     require './HtmlTextNode'    