# generated by Neptune Namespaces v3.x.x
# file: Art/HtmlFactory/namespace.coffee

module.exports = (require '../namespace').addNamespace 'HtmlFactory', class HtmlFactory extends Neptune.PackageNamespace
  @version: require('../../../package.json').version
