// generated by Neptune Namespaces v4.x.x
// file: Art/HtmlFactory/namespace.js

module.exports = require('../namespace').addNamespace(
  'HtmlFactory',
  (class HtmlFactory extends Neptune.PackageNamespace {})
  ._configureNamespace(require('../../../package.json'))
);
