# generated by Neptune Namespaces v3.x.x
# file: tests/Art/HtmlFactory/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  Factories:    require './Factories'   
  HtmlTextNode: require './HtmlTextNode'