// generated by Neptune Namespaces v4.x.x
// file: tests/Art/HtmlFactory/index.js

(module.exports = require('./namespace'))

.addModules({
  Factories:    require('./Factories'),
  HtmlTextNode: require('./HtmlTextNode')
});