# generated by Neptune Namespaces v2.x.x
# file: tests/Art/HtmlFactory/namespace.coffee

Art = require '../namespace'
module.exports = Art.HtmlFactory ||
Art.addNamespace 'HtmlFactory', class HtmlFactory extends Neptune.Base
  ;
