# generated by Neptune Namespaces v0.1.0
# file: my_module_with_both/file_and_module_with_same_name/namespace.coffee

MyModuleWithBoth = require '../namespace'
module.exports = MyModuleWithBoth.FileAndModuleWithSameName ||
MyModuleWithBoth.addNamespace class FileAndModuleWithSameName extends Neptune.Base
  ;