# generated by Neptune Namespaces v2.x.x
# file: Art/BuildConfigurator/FileBuilder/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  Dir:  require './Dir' 
  File: require './File'