// generated by Neptune Namespaces v4.x.x
// file: Art.Build.Configurator/index.js

(module.exports = require('./namespace'))
.includeInNamespace(require('./Configurator'))
.addModules({
  AbcConfigV2:          require('./AbcConfigV2'),
  AbcLog:               require('./AbcLog'),
  Configuration:        require('./Configuration'),
  FsEasy:               require('./FsEasy'),
  Git:                  require('./Git'),
  Initialization:       require('./Initialization'),
  LoadAbcConfig:        require('./LoadAbcConfig'),
  LoadConfig:           require('./LoadConfig'),
  Loaders:              require('./Loaders'),
  Main:                 require('./Main'),
  Publish:              require('./Publish'),
  Recipe:               require('./Recipe'),
  RecipeRegistry:       require('./RecipeRegistry'),
  RunNeptuneNamespaces: require('./RunNeptuneNamespaces'),
  ShellExecSimple:      require('./ShellExecSimple'),
  StandardImport:       require('./StandardImport'),
  Versioning:           require('./Versioning')
});
require('./Configurators');
require('./Data');
require('./Recipes');