# generated by Neptune Namespaces v0.1.0
# file: my_module_directories/_require_first/namespace.coffee

MyModuleDirectories = require '../namespace'
module.exports = MyModuleDirectories.RequireFirst ||
MyModuleDirectories.addNamespace class RequireFirst extends Neptune.Base
  ;