# generated by Neptune Namespaces v1.x.x
# file: art/xbd/index.coffee

module.exports = require './namespace'
.includeInNamespace require './_xbd'
.addModules
  XbdDictionary: require './xbd_dictionary'
  XbdTag:        require './xbd_tag'       