# generated by Neptune Namespaces
# file: art/xbd/index.coffee

module.exports =
Xbd               = require './namespace'
Xbd.Xbd           = require './xbd'
Xbd.XbdDictionary = require './xbd_dictionary'
Xbd.XbdTag        = require './xbd_tag'
Xbd.finishLoad(
  ["Xbd","XbdDictionary","XbdTag"]
)