# generated by Neptune Namespaces
# this file: src/art/xbd/index.coffee

module.exports =
Xbd            = require './namespace'
Xbd.Dictionary = require './dictionary'
Xbd.Tag        = require './tag'
Xbd.Xbd        = require './xbd'
Xbd.finishLoad(
  ["Dictionary","Tag","Xbd"]
)