# generated by Neptune Namespaces
# file: art/xbd/namespace.coffee

Art = require '../namespace'
module.exports = Art.Xbd ||
class Art.Xbd extends Neptune.Base
  @namespace: Art
  @namespacePath: "Neptune.Art.Xbd"

Art.addNamespace Art.Xbd