# generated by Neptune Namespaces v0.1.0
# file: geometry/solids/namespace.coffee

Geometry = require '../namespace'
module.exports = Geometry.Solids ||
Geometry.addNamespace class Solids extends Neptune.Base
  ;