// generated by Neptune Namespaces v4.x.x
// file: tests/index.js

(module.exports = require('./namespace'))

.addModules({
  Array:          require('./Array'),
  Comprehensions: require('./Comprehensions'),
  Each:           require('./Each'),
  Find:           require('./Find'),
  Object:         require('./Object'),
  Reduce:         require('./Reduce'),
  StandardImport: require('./StandardImport')
});