# generated by Neptune Namespaces v2.x.x
# file: tests/Art/StandardLib/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  Array:            require './array'           
  CallStack:        require './CallStack'       
  Clone:            require './clone'           
  Eq:               require './eq'              
  Iteration:        require './Iteration'       
  Map:              require './Map'             
  Math:             require './math'            
  NextTick:         require './nextTick'        
  ObjectDiff:       require './object_diff'     
  ObjectExtensions: require './ObjectExtensions'
  ParseUrl:         require './parse_url'       
  PlainData:        require './plain_data'      
  Promise:          require './promise'         
  Regexp:           require './regexp'          
  Ruby:             require './ruby'            
  StringCase:       require './string_case'     
  String:           require './string'          
  Time:             require './time'            
  Types:            require './types'           
  Unique:           require './unique'          
require './Inspect'