# generated by Neptune Namespaces v3.x.x
# file: tests/Art/StandardLib/namespace.coffee

module.exports = (require '../namespace').addNamespace 'StandardLib', class StandardLib extends Neptune.PackageNamespace
  @version: require('../../../../package.json').version
require './Inspect/namespace'