// generated by Neptune Namespaces v4.x.x
// file: Art.RestClient/namespace.js

module.exports = require('neptune-namespaces').addNamespace(
  'Art.RestClient',
  (class RestClient extends Neptune.PackageNamespace {})
  ._configureNamespace(require('../../package.json'))
);
