# generated by Neptune Namespaces v3.x.x
# file: Art.RestClient/namespace.coffee

module.exports = (require 'neptune-namespaces').addNamespace 'Art.RestClient', class RestClient extends Neptune.PackageNamespace
  @version: require('../../package.json').version
