// generated by Neptune Namespaces v4.x.x
// file: Art.FileBuilder/index.js

(module.exports = require('./namespace'))
.includeInNamespace(require('./FileBuilder'))
.addModules({
  Dir:            require('./Dir'),
  File:           require('./File'),
  StandardImport: require('./StandardImport')
});