// generated by Neptune Namespaces v4.x.x
// file: Art.FileBuilder/namespace.js

module.exports = require('neptune-namespaces').addNamespace(
  'Art.FileBuilder',
  (class FileBuilder extends Neptune.PackageNamespace {})
  ._configureNamespace(require('../../package.json'))
);
