# generated by Neptune Namespaces v3.x.x
# file: tests/Art.BrowserTools/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  DomElementFactories: require './dom_element_factories'
  Test:                require './Test'                 
  Uri:                 require './Uri'                  