// generated by Neptune Namespaces v4.x.x
// file: tests/Art.BrowserTools/index.js

(module.exports = require('./namespace'))

.addModules({
  DomElementFactories: require('./dom_element_factories'),
  Test:                require('./Test'),
  Uri:                 require('./Uri')
});