# generated by Neptune Namespaces v3.x.x
# file: tests/Art.BrowserTools/namespace.coffee

module.exports = (require '../namespace').addNamespace 'Art.BrowserTools', class BrowserTools extends Neptune.PackageNamespace
  @version: require('../../../package.json').version
