// generated by Neptune Namespaces v4.x.x
// file: tests/Art.BrowserTools/namespace.js

module.exports = require('../namespace').addNamespace(
  'Art.BrowserTools',
  (class BrowserTools extends Neptune.PackageNamespace {})
  ._configureNamespace(require('../../../package.json'))
);
