// generated by Neptune Namespaces v4.x.x
// file: tests/Art.FileBuilder/index.js

(module.exports = require('./namespace'))

.addModules({
  Structure: require('./Structure'),
  Write:     require('./Write')
});