// generated by Neptune Namespaces v4.x.x
// file: tests/Art.FileBuilder/namespace.js

module.exports = require('../namespace').addNamespace(
  'Art.FileBuilder',
  (class FileBuilder extends Neptune.PackageNamespace {})
  ._configureNamespace(require('../../../package.json'))
);
