// generated by Neptune Namespaces v4.x.x
// file: tests/Art.Filebuilder/namespace.js

module.exports = require('../namespace').addNamespace(
  'Art.Filebuilder',
  (class Filebuilder extends Neptune.PackageNamespace {})
  ._configureNamespace(require('../../../package.json'))
);
