// generated by Neptune Namespaces v4.x.x
// file: Art.ObjectTreeFactory/namespace.js

module.exports = require('neptune-namespaces').addNamespace(
  'Art.ObjectTreeFactory',
  (class ObjectTreeFactory extends Neptune.PackageNamespace {})
  ._configureNamespace(require('../../package.json'))
);
