# generated by Neptune Namespaces v3.x.x
# file: Art.ObjectTreeFactory/namespace.coffee

module.exports = (require 'neptune-namespaces').addNamespace 'Art.ObjectTreeFactory', class ObjectTreeFactory extends Neptune.PackageNamespace
  @version: require('../../package.json').version
