// generated by Neptune Namespaces v3.x.x
// file: tests/Art/BuildConfigurator/FileBuilder/index.js

(module.exports = require('./namespace'))

.addModules({
  Structure: require('./Structure'),
  Write:     require('./Write')
});