# generated by Neptune Namespaces v2.x.x
# file: tests/Art/BuildConfigurator/FileBuilder/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  Structure: require './Structure'