// generated by Neptune Namespaces v4.x.x
// file: tests/Art/BuildConfigurator/FileBuilder/namespace.js

module.exports = require('../namespace').addNamespace(
  'FileBuilder',
  (class FileBuilder extends Neptune.PackageNamespace {})
  ._configureNamespace(require('../../../../../package.json'))
);
