# generated by Neptune Namespaces v2.x.x
# file: tests/Art/BuildConfigurator/FileBuilder/namespace.coffee

BuildConfigurator = require '../namespace'
module.exports = BuildConfigurator.FileBuilder ||
BuildConfigurator.addNamespace 'FileBuilder', class FileBuilder extends Neptune.Base
  ;
