# generated by Neptune Namespaces v3.x.x
# file: tests/Art/BuildConfigurator/FileBuilder/namespace.coffee

module.exports = (require '../namespace').addNamespace 'FileBuilder', class FileBuilder extends Neptune.PackageNamespace
  @version: require('../../../../../package.json').version
