# generated by Neptune Namespaces v2.x.x
# file: tests/Art/BuildConfigurator/namespace.coffee

Art = require '../namespace'
module.exports = Art.BuildConfigurator ||
Art.addNamespace 'BuildConfigurator', class BuildConfigurator extends Neptune.Base
  ;
