# generated by Neptune Namespaces v3.x.x
# file: tests/Art/BuildConfigurator/namespace.coffee

module.exports = (require '../namespace').vivifySubnamespace 'BuildConfigurator'
require './FileBuilder/namespace'