// generated by Neptune Namespaces v4.x.x
// file: tests/Art/BuildConfigurator/namespace.js

module.exports = module.exports =  require('../namespace').vivifySubnamespace('BuildConfigurator');
require('./Command/namespace');