# generated by Neptune Namespaces v1.x.x
# file: geometry/solids/namespace.coffee

Geometry = require '../namespace'
module.exports = Geometry.Solids ||
Geometry.addNamespace 'Solids', class Solids extends Neptune.Base
  ;