# generated by Neptune Namespaces v1.x.x
# file: geometry/namespace.coffee

Neptune = require 'neptune-namespaces'
module.exports = Neptune.Geometry ||
Neptune.addNamespace 'Geometry', class Geometry extends Neptune.Base
  ;