# generated by Neptune Namespaces v2.x.x
# file: Art/CommunicationStatus/namespace.coffee

Art = require '../namespace'
module.exports = Art.CommunicationStatus ||
Art.addNamespace 'CommunicationStatus', class CommunicationStatus extends Neptune.Base
  ;
