// generated by Neptune Namespaces v4.x.x
// file: Art/CommunicationStatus/namespace.js

module.exports = require('../namespace').addNamespace(
  'CommunicationStatus',
  (class CommunicationStatus extends Neptune.PackageNamespace {})
  ._configureNamespace(require('../../../package.json'))
);
