# generated by Neptune Namespaces v3.x.x
# file: Art/CommunicationStatus/namespace.coffee

module.exports = (require '../namespace').addNamespace 'CommunicationStatus', class CommunicationStatus extends Neptune.PackageNamespace
  @version: require('../../../package.json').version
