# generated by Neptune Namespaces v0.1.0
# file: geometry/shapes/namespace.coffee

Geometry = require '../namespace'
module.exports = Geometry.Shapes ||
Geometry.addNamespace class Shapes extends Neptune.Base
  ;