# generated by Neptune Namespaces v2.x.x
# file: Runtime/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  Function:           require './function'          
  Global:             require './global'            
  NamespaceBaseClass: require './NamespaceBaseClass'
  Neptune:            require './Neptune'           