# generated by Neptune Namespaces v1.x.x
# file: Runtime/index.coffee

module.exports = require './namespace'
.addModules
  Function: require './function'
  Global:   require './global'  
  Neptune:  require './Neptune' 