// generated by Neptune Namespaces v4.x.x
// file: Art.StandardLib/index.js

(module.exports = require('./namespace'))
.includeInNamespace(require('./StandardLib'))
.addModules({
  ArrayExtensions:    require('./ArrayExtensions'),
  AsyncExtensions:    require('./AsyncExtensions'),
  CallStack:          require('./CallStack'),
  Clone:              require('./Clone'),
  CommonJs:           require('./CommonJs'),
  DateExtensions:     require('./DateExtensions'),
  Environment:        require('./Environment'),
  Eq:                 require('./Eq'),
  ErrorWithInfo:      require('./ErrorWithInfo'),
  FunctionExtensions: require('./FunctionExtensions'),
  Iteration:          require('./Iteration'),
  Log:                require('./Log'),
  Map:                require('./Map'),
  MapExtensions:      require('./MapExtensions'),
  MathExtensions:     require('./MathExtensions'),
  MinimalBaseObject:  require('./MinimalBaseObject'),
  ObjectDiff:         require('./ObjectDiff'),
  ObjectExtensions:   require('./ObjectExtensions'),
  ParseUrl:           require('./ParseUrl'),
  Promise:            require('./Promise'),
  PromisedFileReader: require('./PromisedFileReader'),
  PromiseWorkerPool:  require('./PromiseWorkerPool'),
  RegExpExtensions:   require('./RegExpExtensions'),
  RequestError:       require('./RequestError'),
  ReschedulableTimer: require('./ReschedulableTimer'),
  Ruby:               require('./Ruby'),
  ShallowClone:       require('./ShallowClone'),
  StringExtensions:   require('./StringExtensions'),
  Time:               require('./Time'),
  TypesExtended:      require('./TypesExtended'),
  Unique:             require('./Unique')
});
require('./Core');
require('./Inspect');