// generated by Neptune Namespaces v4.x.x
// file: Art.StandardLib/namespace.js

module.exports = require('neptune-namespaces').addNamespace(
  'Art.StandardLib',
  (class StandardLib extends Neptune.PackageNamespace {})
  ._configureNamespace(require('../../package.json'))
);
require('./Core/namespace');
require('./Inspect/namespace');