# generated by Neptune Namespaces v3.x.x
# file: Art.StandardLib/namespace.coffee

module.exports = (require 'neptune-namespaces').addNamespace('Art.StandardLib', class StandardLib extends Neptune.PackageNamespace)
require './Core/namespace';
require './Inspect/namespace'