import { createRequire } from 'module';
const require = createRequire(import.meta.url);

export const {
  abs,
  absGt,
  absGte,
  absLt,
  absLte,
  boolRand,
  bound,
  ceil,
  commaize,
  cyclingSequenceFunction,
  float32Eq,
  float32Eq0,
  float32Gt,
  float32Gte,
  float32Lt,
  float32Lte,
  float32Precision,
  float32True0,
  float64Precision,
  floatEq,
  floatEq0,
  floatGt,
  floatGte,
  floatLt,
  floatLte,
  floatTrue0,
  floor,
  fPart,
  intRand,
  iPart,
  max,
  maxChange,
  maxMagnitude,
  min,
  minMagnitude,
  modulo,
  nearInfinity,
  nearInfinityResult,
  numberToTightString,
  random,
  round,
  seededRandomNumberGenerator,
  simplifyNum,
  stringToNumberArray,
} = require('./build');
