// generated by Neptune Namespaces v4.x.x
// file: Art.HtmlFactory/index.js

(module.exports = require('./namespace'))
.includeInNamespace(require('./HtmlFactory'))
.addModules({
  HtmlFactoryLib: require('./HtmlFactoryLib'),
  HtmlLib:        require('./HtmlLib'),
  HtmlTextNode:   require('./HtmlTextNode')
});