# generated by Neptune Namespaces v0.1.0
# file: my_module_with_both/index.coffee

require './-loaded_but_not_added_file'
require './-loaded_but_not_added_directory'
(module.exports = require './namespace')
.addModules
  FileAndModuleWithSameName: require './file_and_module_with_same_name'
  NormalFile:                require './normal_file'
require './normal_directory'