# generated by Neptune Namespaces v0.1.0
# file: my_module_with_both/namespace.coffee

require 'neptune-namespaces'
module.exports = Neptune.MyModuleWithBoth ||
Neptune.addNamespace class MyModuleWithBoth extends Neptune.Base
  ;