// generated by Neptune Namespaces v4.x.x
// file: Art/EpochedState/index.js

(module.exports = require('./namespace'))
.includeInNamespace(require('./EpochedState'))
.addModules({
  EpochClass: require('./EpochClass')
});