# generated by Neptune Namespaces v1.x.x
# file: Art/ObjectTreeFactory/namespace.coffee

Art = require '../namespace'
module.exports = Art.ObjectTreeFactory ||
Art.addNamespace 'ObjectTreeFactory', class ObjectTreeFactory extends Neptune.Base
  ;