# generated by Neptune Namespaces v2.x.x
# file: tests/Runtime/namespace.coffee

Tests = require '../namespace'
module.exports = Tests.Runtime ||
Tests.addNamespace 'Runtime', class Runtime extends Neptune.Base
  ;
