// generated by Neptune Namespaces v4.x.x
// file: jest/index.js

(module.exports = require('./namespace'))

.addModules({
  HelpTest:       require('./Help.test'),
  MainTest:       require('./Main.test'),
  ParseTest:      require('./Parse.test'),
  StandardImport: require('./StandardImport')
});