// generated by Neptune Namespaces v4.x.x
// file: ArtSuite.Ace/index.js

(module.exports = require('./namespace'))
.includeInNamespace(require('./Ace'))
.addModules({
  AceMain:        require('./AceMain'),
  LoadAceConfig:  require('./LoadAceConfig'),
  StandardImport: require('./StandardImport')
});