// generated by Neptune Namespaces v4.x.x
// file: Art.Foundation/index.js

(module.exports = require('./namespace'))
.includeInNamespace(require('./Foundation'))
.addModules({
  ArtFoundationConfig: require('./ArtFoundationConfig'),
  Binary:              require('./Binary')
});
require('./ForHumans');
require('./Tools');