// generated by Neptune Namespaces v4.x.x
// file: perfs/art/foundation/index.js

(module.exports = require('./namespace'))

.addModules({
  Eq:            require('./eq'),
  Hash:          require('./hash'),
  StringParsing: require('./string_parsing'),
  Types:         require('./types'),
  Unique:        require('./unique')
});
require('./binary');