// generated by Neptune Namespaces v4.x.x
// file: perfs/art/foundation/namespace.js

module.exports = require('../namespace').addNamespace(
  'Foundation',
  class Foundation extends Neptune.PackageNamespace {}
);
require('./binary/namespace');