# generated by Neptune Namespaces v3.x.x
# file: Art/EpochedState/index.coffee

module.exports = require './namespace'
module.exports
.includeInNamespace require './EpochedState'
.addModules
  EpochClass: require './EpochClass'