# generated by Neptune Namespaces v2.x.x
# file: Art/EpochedState/namespace.coffee

Art = require '../namespace'
module.exports = Art.EpochedState ||
Art.addNamespace 'EpochedState', class EpochedState extends Neptune.Base
  ;
