# generated by Neptune Namespaces v3.x.x
# file: Art/EpochedState/namespace.coffee

module.exports = (require '../namespace').addNamespace 'EpochedState', class EpochedState extends Neptune.PackageNamespace
  @version: require('../../../package.json').version
