// generated by Neptune Namespaces v4.x.x
// file: tests/Art.ClassSystem/index.js

(module.exports = require('./namespace'))

.addModules({
  DeclarableMixin:           require('./DeclarableMixin'),
  ExtendedablePropertyMixin: require('./ExtendedablePropertyMixin'),
  SingletonClass:            require('./SingletonClass')
});
require('./BaseClass');