// generated by Neptune Namespaces v4.x.x
// file: tests/Art.ClassSystem/namespace.js

module.exports = require('../namespace').addNamespace(
  'Art.ClassSystem',
  (class ClassSystem extends Neptune.PackageNamespace {})
  ._configureNamespace(require('../../../package.json'))
);
require('./BaseClass/namespace');