# generated by Neptune Namespaces v3.x.x
# file: tests/Art.ClassSystem/namespace.coffee

module.exports = (require '../namespace').addNamespace 'Art.ClassSystem', class ClassSystem extends Neptune.PackageNamespace
  @version: require('../../../package.json').version
require './BaseClass/namespace'