// generated by Neptune Namespaces v4.x.x
// file: tests/Art.Xbd/index.js

(module.exports = require('./namespace'))

.addModules({
  BuildXbd: require('./BuildXbd'),
  FromXbd:  require('./FromXbd'),
  ToXbd:    require('./toXbd')
});