# generated by Neptune Namespaces v3.x.x
# file: tests/Art.Xbd/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  BuildXbd: require './BuildXbd'
  FromXbd:  require './FromXbd' 
  ToXbd:    require './toXbd'   