# generated by Neptune Namespaces v3.x.x
# file: tests/Art.Xbd/namespace.coffee

module.exports = (require '../namespace').addNamespace 'Art.Xbd', class Xbd extends Neptune.PackageNamespace
  @version: require('../../../package.json').version
