// generated by Neptune Namespaces v4.x.x
// file: tests/Art.Xbd/namespace.js

module.exports = require('../namespace').addNamespace(
  'Art.Xbd',
  (class Xbd extends Neptune.PackageNamespace {})
  ._configureNamespace(require('../../../package.json'))
);
