# generated by Neptune Namespaces v3.x.x
# file: Art/Events/namespace.coffee

module.exports = (require '../namespace').addNamespace 'Events', class Events extends Neptune.PackageNamespace
  @version: require('../../../package.json').version
