# generated by Neptune Namespaces v2.x.x
# file: Art/Events/namespace.coffee

Art = require '../namespace'
module.exports = Art.Events ||
Art.addNamespace 'Events', class Events extends Neptune.Base
  ;
