// generated by Neptune Namespaces v4.x.x
// file: Art/Events/namespace.js

module.exports = require('../namespace').addNamespace(
  'Events',
  (class Events extends Neptune.PackageNamespace {})
  ._configureNamespace(require('../../../package.json'))
);
