# generated by Neptune Namespaces v3.x.x
# file: Art.Binary/index.coffee

module.exports = require './namespace'
module.exports
.includeInNamespace require './Binary'
.addModules
  BinaryString:            require './BinaryString'           
  DataUri:                 require './DataUri'                
  EncodedImage:            require './EncodedImage'           
  File:                    require './File'                   
  Stream:                  require './Stream'                 
  TypedarraySlicePolyfill: require './TypedarraySlicePolyfill'
  Utf8:                    require './Utf8'                   
  WriteStream:             require './WriteStream'            