// generated by Neptune Namespaces v4.x.x
// file: Art.Binary/index.js

(module.exports = require('./namespace'))
.includeInNamespace(require('./Binary'))
.addModules({
  BinaryString:            require('./BinaryString'),
  DataUri:                 require('./DataUri'),
  EncodedImage:            require('./EncodedImage'),
  File:                    require('./File'),
  Stream:                  require('./Stream'),
  TypedarraySlicePolyfill: require('./TypedarraySlicePolyfill'),
  Utf8:                    require('./Utf8'),
  WriteStream:             require('./WriteStream')
});