# generated by Neptune Namespaces v3.x.x
# file: Art.Binary/namespace.coffee

module.exports = (require 'neptune-namespaces').addNamespace 'Art.Binary', class Binary extends Neptune.PackageNamespace
  @version: require('../../package.json').version
