// generated by Neptune Namespaces v4.x.x
// file: Art.Binary/namespace.js

module.exports = require('neptune-namespaces').addNamespace(
  'Art.Binary',
  (class Binary extends Neptune.PackageNamespace {})
  ._configureNamespace(require('../../package.json'))
);
