// generated by Neptune Namespaces v4.x.x
// file: Art.Foundation/Tools/index.js

(module.exports = require('./namespace'))
.includeInNamespace(require('./Tools'))
.addModules({
  Analytics:                    require('./Analytics'),
  AsyncLocalStorage:            require('./AsyncLocalStorage'),
  BatchLoader:                  require('./BatchLoader'),
  GlobalCounts:                 require('./GlobalCounts'),
  InstanceFunctionBindingMixin: require('./InstanceFunctionBindingMixin'),
  JsonStore:                    require('./JsonStore'),
  ProgressAdapter:              require('./ProgressAdapter'),
  SingleObjectTransaction:      require('./SingleObjectTransaction'),
  Stat:                         require('./Stat'),
  Transaction:                  require('./Transaction'),
  WebWorker:                    require('./WebWorker'),
  WorkerRpc:                    require('./WorkerRpc')
});