# generated by Neptune Namespaces v3.x.x
# file: tests/Art.StandardLib/Core/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  Merge:          require './Merge'
  StandardImport: require './StandardImport'