// generated by Neptune Namespaces v4.x.x
// file: tests/Art.StandardLib/Core/index.js

(module.exports = require('./namespace'))

.addModules({
  Merge:          require('./Merge'),
  StandardImport: require('./StandardImport')
});