# generated by Neptune Namespaces v2.x.x
# file: Art/StandardLib/namespace.coffee

Art = require '../namespace'
module.exports = Art.StandardLib ||
Art.addNamespace 'StandardLib', class StandardLib extends Neptune.Base
  ;
require './Core/namespace';
require './Inspect/namespace'