# generated by Neptune Namespaces
# file: tests/art/events/index.coffee

(module.exports = require './namespace')
.addModules
  EventManager:  require './event_manager'
  EventQueue:    require './event_queue'
  EventedObject: require './evented_object'
