# generated by Neptune Namespaces v1.x.x
# file: tests/art/events/index.coffee

module.exports = require './namespace'
.addModules
  EventedObject: require './EventedObject'
  EventManager:  require './EventManager' 