# generated by Neptune Namespaces
# this file: test/tests/art/events/index.coffee

module.exports =
Events               = require './namespace'
Events.EventManager  = require './event_manager'
Events.EventQueue    = require './event_queue'
Events.EventedObject = require './evented_object'
Events.finishLoad(
  ["EventManager","EventQueue","EventedObject"]
)