# generated by Neptune Namespaces v0.3.0
# file: tests/art/events/namespace.coffee

Art = require '../namespace'
module.exports = Art.Events ||
Art.addNamespace 'Events', class Events extends Neptune.Base
  ;