# generated by Neptune Namespaces v3.x.x
# file: Art.ClassSystem/namespace.coffee

module.exports = (require 'neptune-namespaces').addNamespace 'Art.ClassSystem', class ClassSystem extends Neptune.PackageNamespace
  @version: require('../../package.json').version
