// generated by Neptune Namespaces v4.x.x
// file: Art.ClassSystem/namespace.js

module.exports = require('neptune-namespaces').addNamespace(
  'Art.ClassSystem',
  (class ClassSystem extends Neptune.PackageNamespace {})
  ._configureNamespace(require('../../package.json'))
);
