// generated by Neptune Namespaces v4.x.x
// file: tests/Art.Build.Configurator/Command/namespace.js

module.exports = require('../namespace').addNamespace(
  'Command',
  class Command extends Neptune.PackageNamespace {}
);
