# generated by Neptune Namespaces v2.x.x
# file: Art/StandardLib/Inspect/Inspected/namespace.coffee

Inspect = require '../namespace'
module.exports = Inspect.Inspected ||
Inspect.addNamespace 'Inspected', class Inspected extends Neptune.Base
  ;
