# generated by Neptune Namespaces v0.1.0
# file: art/events/index.coffee

(module.exports = require './namespace')
.includeInNamespace(require './_events')
.addModules
  Event:             require './event'
  EventEpoch:        require './event_epoch'
  EventManager:      require './event_manager'
  EventQueue:        require './event_queue'
  EventedObject:     require './evented_object'
  EventedObjectBase: require './evented_object_base'
  EventedVariable:   require './evented_variable'