# generated by Neptune Namespaces v0.5
# file: art/events/namespace.coffee

Art = require '../namespace'
module.exports = Art.Events ||
Art.addNamespace 'Events', class Events extends Neptune.Base
  ;