# generated by Neptune Namespaces
# file: src/art/events/namespace.coffee

Art = require '../namespace'
module.exports = Art.Events ||
class Art.Events extends Neptune.Base
  @namespace: Art
  @namespacePath: "Neptune.Art.Events"

Art.addNamespace Art.Events