// generated by Neptune Namespaces v4.x.x
// file: tests/Art.Validation/index.js

(module.exports = require('./namespace'))

.addModules({
  Limits:         require('./Limits'),
  PostValidation: require('./PostValidation'),
  SubValidation:  require('./SubValidation'),
  Validator:      require('./Validator')
});