# generated by Neptune Namespaces v3.x.x
# file: tests/Art.Validation/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  Limits:         require './Limits'        
  PostValidation: require './PostValidation'
  SubValidation:  require './SubValidation' 
  Validator:      require './Validator'     