# generated by Neptune Namespaces v3.x.x
# file: tests/Art.Validation/namespace.coffee

module.exports = (require '../namespace').addNamespace 'Art.Validation', class Validation extends Neptune.PackageNamespace
  @version: require('../../../package.json').version
