// generated by Neptune Namespaces v4.x.x
// file: tests/Art.Validation/namespace.js

module.exports = require('../namespace').addNamespace(
  'Art.Validation',
  (class Validation extends Neptune.PackageNamespace {})
  ._configureNamespace(require('../../../package.json'))
);
