# generated by Neptune Namespaces v0.1.0
# file: geometry/namespace.coffee

require 'neptune-namespaces'
module.exports = Neptune.Geometry ||
Neptune.addNamespace class Geometry extends Neptune.Base
  ;