// generated by Neptune Namespaces v4.x.x
// file: Art.Validation/index.js

(module.exports = require('./namespace'))
.includeInNamespace(require('./Validation'))
.addModules({
  DataTypes:  require('./DataTypes'),
  FieldTypes: require('./FieldTypes'),
  Validator:  require('./Validator')
});