# generated by Neptune Namespaces v3.x.x
# file: Art.Validation/namespace.coffee

module.exports = (require 'neptune-namespaces').addNamespace 'Art.Validation', class Validation extends Neptune.PackageNamespace
  @version: require('../../package.json').version
