// generated by Neptune Namespaces v4.x.x
// file: Art.Validation/namespace.js

module.exports = require('neptune-namespaces').addNamespace(
  'Art.Validation',
  (class Validation extends Neptune.PackageNamespace {})
  ._configureNamespace(require('../../package.json'))
);
