# generated by Neptune Namespaces v3.x.x
# file: Art.EmailValidator/index.coffee

module.exports = require './namespace'
module.exports
.includeInNamespace require './EmailValidator'
.addModules
  DomainValidation:  require './DomainValidation' 
  MailboxValidation: require './MailboxValidation'
  RegExp:            require './RegExp'           
  StandardImport:    require './StandardImport'   
  Verbose:           require './Verbose'          