// generated by Neptune Namespaces v4.x.x
// file: Art.EmailValidator/index.js

(module.exports = require('./namespace'))
.includeInNamespace(require('./EmailValidator'))
.addModules({
  DomainValidation:  require('./DomainValidation'),
  MailboxValidation: require('./MailboxValidation'),
  RegExp:            require('./RegExp'),
  Smtp:              require('./Smtp'),
  StandardImport:    require('./StandardImport'),
  Verbose:           require('./Verbose')
});