// generated by Neptune Namespaces v4.x.x
// file: Art.EmailValidator/namespace.js

module.exports = require('neptune-namespaces-runtime').addNamespace(
  'Art.EmailValidator',
  (class EmailValidator extends Neptune.PackageNamespace {})
  ._configureNamespace(require('../../package.json'))
);
