# generated by Neptune Namespaces v3.x.x
# file: Art.EmailValidator/namespace.coffee

module.exports = (require 'neptune-namespaces').addNamespace 'Art.EmailValidator', class EmailValidator extends Neptune.PackageNamespace
  @version: require('../../package.json').version
