# generated by Neptune Namespaces v2.x.x
# file: Generation/Generators/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  IndexGenerator:     require './IndexGenerator'    
  NamespaceGenerator: require './NamespaceGenerator'