# generated by Neptune Namespaces v2.x.x
# file: Generation/Generators/namespace.coffee

Generation = require '../namespace'
module.exports = Generation.Generators ||
Generation.addNamespace 'Generators', class Generators extends Neptune.Base
  ;
