# generated by Neptune Namespaces v3.x.x
# file: Generation/Generators/namespace.coffee

module.exports = (require '../namespace').addNamespace('Generators', class Generators extends Neptune.PackageNamespace)
