// generated by Neptune Namespaces v4.x.x
// file: test/Art.Config/namespace.js

module.exports = require('../namespace').addNamespace(
  'Art.Config',
  class Config extends Neptune.PackageNamespace {}
);
