# generated by Neptune Namespaces v3.x.x
# file: tests/Art.Binary/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  BinaryString:   require './BinaryString'  
  EncodedImage:   require './EncodedImage'  
  StandardImport: require './StandardImport'
  Utf8:           require './Utf8'          
  WriteStream:    require './WriteStream'   