// generated by Neptune Namespaces v4.x.x
// file: tests/Art.Binary/index.js

(module.exports = require('./namespace'))

.addModules({
  BinaryString:   require('./BinaryString'),
  EncodedImage:   require('./EncodedImage'),
  StandardImport: require('./StandardImport'),
  Utf8:           require('./Utf8'),
  WriteStream:    require('./WriteStream')
});