# generated by Neptune Namespaces v3.x.x
# file: tests/Art.Binary/namespace.coffee

module.exports = (require '../namespace').addNamespace 'Art.Binary', class Binary extends Neptune.PackageNamespace
  @version: require('../../../package.json').version
