// generated by Neptune Namespaces v4.x.x
// file: tests/Art.Binary/namespace.js

module.exports = require('../namespace').addNamespace(
  'Art.Binary',
  (class Binary extends Neptune.PackageNamespace {})
  ._configureNamespace(require('../../../package.json'))
);
