// generated by Neptune Namespaces v4.x.x
// file: tests/Art.EpochedState/namespace.js

module.exports = require('../namespace').addNamespace(
  'Art.EpochedState',
  (class EpochedState extends Neptune.PackageNamespace {})
  ._configureNamespace(require('../../../package.json'))
);
