# generated by Neptune Namespaces v3.x.x
# file: tests/Art.EpochedState/namespace.coffee

module.exports = (require '../namespace').addNamespace 'Art.EpochedState', class EpochedState extends Neptune.PackageNamespace
  @version: require('../../../package.json').version
