// generated by Neptune Namespaces v4.x.x
// file: test/index.js

(module.exports = require('./namespace'))

.addModules({
  ConfigRegistryTest:           require('./ConfigRegistry.test'),
  ConfigurationInheritanceTest: require('./ConfigurationInheritance.test'),
  LibTest:                      require('./Lib.test'),
  StandardImport:               require('./StandardImport'),
  TestConfigurableTest:         require('./TestConfigurable.test')
});
require('./Art.Config');