# generated by Neptune Namespaces v1.x.x
# file: Art/Config/index.coffee

module.exports = require './namespace'
.includeInNamespace require './Config'
.addModules
  ConfigRegistry: require './ConfigRegistry'
  Configurable:   require './Configurable'  
  Configuration:  require './Configuration' 