# generated by Neptune Namespaces v1.x.x
# file: Art/Config/namespace.coffee

Art = require '../namespace'
module.exports = Art.Config ||
Art.addNamespace 'Config', class Config extends Neptune.Base
  ;