// generated by Neptune Namespaces v4.x.x
// file: perfs/art/foundation/binary/namespace.js

module.exports = require('../namespace').addNamespace(
  'Binary',
  class Binary extends Neptune.PackageNamespace {}
);
