// generated by Neptune Namespaces v4.x.x
// file: tests/Art.Cli/namespace.js

module.exports = require('../namespace').addNamespace(
  'Art.Cli',
  (class Cli extends Neptune.PackageNamespace {})
  ._configureNamespace(require('../../../package.json'))
);
