# generated by Neptune Namespaces v1.x.x
# file: Art/BuildConfigurator/Data/index.coffee

module.exports = require './namespace'
.addModules
  StandardDependencies:  require './StandardDependencies' 
  StandardPackageJson:   require './StandardPackageJson'  
  StandardWebpackConfig: require './StandardWebpackConfig'