# generated by Neptune Namespaces v1.x.x
# file: Art/BuildConfigurator/Data/namespace.coffee

BuildConfigurator = require '../namespace'
module.exports = BuildConfigurator.Data ||
BuildConfigurator.addNamespace 'Data', class Data extends Neptune.Base
  ;