// generated by Neptune Namespaces v4.x.x
// file: tests/Art/namespace.js

module.exports = require('../namespace').addNamespace(
  'Art',
  (class Art extends Neptune.PackageNamespace {})
  ._configureNamespace(require('../../../package.json'))
);
