// generated by Neptune Namespaces v4.x.x
// file: tests/Art.Config/index.js

(module.exports = require('./namespace'))

.addModules({
  ConfigRegistry:           require('./ConfigRegistry'),
  ConfigurationInheritance: require('./ConfigurationInheritance'),
  Lib:                      require('./Lib'),
  TestConfig:               require('./TestConfig'),
  TestConfigurable:         require('./TestConfigurable')
});