# generated by Neptune Namespaces v3.x.x
# file: tests/Art.Config/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  ConfigRegistry:           require './ConfigRegistry'          
  ConfigurationInheritance: require './ConfigurationInheritance'
  Lib:                      require './Lib'                     
  TestConfig:               require './TestConfig'              
  TestConfigurable:         require './TestConfigurable'        