# generated by Neptune Namespaces v0.x.x
# file: tests/Generation/index.coffee

module.exports = require './namespace'
.addModules
  Generator:          require './Generator'         
  NamespaceStructure: require './NamespaceStructure'