// generated by Neptune Namespaces v3.x.x
// file: tests/Generation/index.js

(module.exports = require('./namespace'))

.addModules({
  Generator:          require('./Generator'),
  NamespaceStructure: require('./NamespaceStructure'),
  Pathing:            require('./Pathing')
});