# generated by Neptune Namespaces v2.x.x
# file: tests/Generation/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  Generator:          require './Generator'         
  NamespaceStructure: require './NamespaceStructure'