# generated by Neptune Namespaces v2.x.x
# file: tests/Generation/namespace.coffee

Tests = require '../namespace'
module.exports = Tests.Generation ||
Tests.addNamespace 'Generation', class Generation extends Neptune.Base
  ;
