# generated by Neptune Namespaces v0.4.4
# file: tests/Generation/namespace.coffee

Tests = require '../namespace'
module.exports = Tests.Generation ||
Tests.addNamespace 'Generation', class Generation extends Neptune.Base
  ;