// generated by Neptune Namespaces v4.x.x
// file: tests/Generation/namespace.js

module.exports = require('../namespace').addNamespace(
  'Generation',
  class Generation extends Neptune.PackageNamespace {}
);
