// generated by Neptune Namespaces v4.x.x
// file: Jest/index.js

(module.exports = require('./namespace'))

.addModules({
  FactoriesTest:    require('./Factories.test'),
  HtmlTextNodeTest: require('./HtmlTextNode.test'),
  StandardImport:   require('./StandardImport')
});