// generated by Neptune Namespaces v4.x.x
// file: Art.JsonStore/index.js

(module.exports = require('./namespace'))
.includeInNamespace(require('./JsonStore'))
.addModules({
  AsyncLocalStorage: require('./AsyncLocalStorage'),
  StandardImport:    require('./StandardImport')
});