// generated by Neptune Namespaces v4.x.x
// file: Art.JsonStore/namespace.js

module.exports = require('neptune-namespaces-runtime').addNamespace(
  'Art.JsonStore',
  (class JsonStore extends Neptune.PackageNamespace {})
  ._configureNamespace(require('../../package.json'))
);
