// generated by Neptune Namespaces v4.x.x
// file: tests/Art.ObjectTreeFactory/index.js

(module.exports = require('./namespace'))

.addModules({
  CreateObjectTreeFactory: require('./CreateObjectTreeFactory'),
  TestClass:               require('./TestClass'),
  UsingFactories:          require('./UsingFactories')
});