# generated by Neptune Namespaces v3.x.x
# file: tests/Art.ObjectTreeFactory/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  CreateObjectTreeFactory: require './CreateObjectTreeFactory'
  TestClass:               require './TestClass'              
  UsingFactories:          require './UsingFactories'         