# generated by Neptune Namespaces v3.x.x
# file: tests/Art.ObjectTreeFactory/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  Basics:                  require './Basics'                 
  CreateObjectTreeFactory: require './createObjectTreeFactory'