# generated by Neptune Namespaces v3.x.x
# file: tests/Art.ObjectTreeFactory/namespace.coffee

module.exports = (require '../namespace').addNamespace 'Art.ObjectTreeFactory', class ObjectTreeFactory extends Neptune.PackageNamespace
  @version: require('../../../package.json').version
