// generated by Neptune Namespaces v4.x.x
// file: tests/Art.ObjectTreeFactory/namespace.js

module.exports = require('../namespace').addNamespace(
  'Art.ObjectTreeFactory',
  class ObjectTreeFactory extends Neptune.PackageNamespace {}
);
