// generated by Neptune Namespaces v4.x.x
// file: tests/art/namespace.js

module.exports = require('../namespace').addNamespace(
  'Art',
  (class Art extends Neptune.PackageNamespace {})
  ._configureNamespace(require('../../../package.json'))
);
require('./dev_tools/namespace');
require('./foundation/namespace');