// generated by Neptune Namespaces v4.x.x
// file: Art.Filebuilder/index.js

(module.exports = require('./namespace'))

.addModules({
  Dir:            require('./Dir'),
  File:           require('./File'),
  FileBuilder:    require('./FileBuilder'),
  StandardImport: require('./StandardImport')
});