// generated by Neptune Namespaces v4.x.x
// file: Art.Filebuilder/namespace.js

module.exports = require('neptune-namespaces').addNamespace(
  'Art.Filebuilder',
  (class Filebuilder extends Neptune.PackageNamespace {})
  ._configureNamespace(require('../../package.json'))
);
