// generated by Neptune Namespaces v4.x.x
// file: ArtSuite.Cli/namespace.js

module.exports = require('neptune-namespaces').addNamespace(
  'ArtSuite.Cli',
  (class Cli extends Neptune.PackageNamespace {})
  ._configureNamespace(require('../../package.json'))
);
