# generated by Neptune Namespaces v0.1.0
# file: my_module_directories/index.coffee

require './-required_but_not_added'
(module.exports = require './namespace')
require './_require_first'
require './my_module_directories'
require './normal_name'