# generated by Neptune Namespaces v0.1.0
# file: my_module_directories/namespace.coffee

require 'neptune-namespaces'
module.exports = Neptune.MyModuleDirectories ||
Neptune.addNamespace class MyModuleDirectories extends Neptune.Base
  ;