# generated by Neptune Namespaces
# file: tests/art/xbd/index.coffee

module.exports =
Xbd                       = require './namespace'
Xbd.FromXbd               = require './from_xbd'
Xbd.ReadFileAsArrayBuffer = require './read_file_as_array_buffer'
Xbd.ToXbd                 = require './to_xbd'
Xbd.finishLoad(
  ["FromXbd","ReadFileAsArrayBuffer","ToXbd"]
)