# generated by Neptune Namespaces v0.3.0
# file: tests/art/xbd/index.coffee

(module.exports = require './namespace')
.addModules
  BuildXbd:              require './build_xbd'
  FromXbd:               require './from_xbd'
  ReadFileAsArrayBuffer: require './read_file_as_array_buffer'
  ToXbd:                 require './to_xbd'