// generated by Neptune Namespaces v4.x.x
// file: Art.Events/index.js

(module.exports = require('./namespace'))

.addModules({
  Event:                  require('./Event'),
  EventedBaseMixin:       require('./EventedBaseMixin'),
  EventedMixin:           require('./EventedMixin'),
  EventedObject:          require('./EventedObject'),
  EventEpoch:             require('./EventEpoch'),
  EventManager:           require('./EventManager'),
  ExtendableEventedMixin: require('./ExtendableEventedMixin')
});