// generated by Neptune Namespaces v4.x.x
// file: test/tests/namespace.js

module.exports = module.exports =  require('../namespace').vivifySubnamespace('Tests');
require('./Art.StandardLib/namespace');