// generated by Neptune Namespaces v4.x.x
// file: ArtSuite.Ace/namespace.js

module.exports = require('neptune-namespaces-runtime').addNamespace(
  'ArtSuite.Ace',
  (class Ace extends Neptune.PackageNamespace {})
  ._configureNamespace(require('../../package.json'))
);
