// generated by Neptune Namespaces v4.x.x
// file: tests/Art.Build.Configurator/index.js

(module.exports = require('./namespace'))

.addModules({
  StandardImport: require('./StandardImport'),
  Webpack:        require('./Webpack')
});
require('./Command');