// generated by Neptune Namespaces v4.x.x
// file: tests/Art.Build.Configurator/namespace.js

module.exports = module.exports =  require('../namespace').vivifySubnamespace('Art.Build.Configurator');
require('./Command/namespace');