// generated by Neptune Namespaces v4.x.x
// file: tests/Art.Build.Configurator/namespace.js

module.exports = require('../namespace').addNamespace(
  'Art.Build.Configurator',
  class Configurator extends Neptune.PackageNamespace {}
);
require('./Command/namespace');