# generated by Neptune Namespaces v3.x.x
# file: tests/Art.Events/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  EventedMixin: require './EventedMixin'
  EventManager: require './EventManager'