// generated by Neptune Namespaces v4.x.x
// file: tests/Art.Events/index.js

(module.exports = require('./namespace'))

.addModules({
  EventedMixin: require('./EventedMixin'),
  EventManager: require('./EventManager')
});