// generated by Neptune Namespaces v4.x.x
// file: tests/Art.Events/namespace.js

module.exports = require('../namespace').addNamespace(
  'Art.Events',
  (class Events extends Neptune.PackageNamespace {})
  ._configureNamespace(require('../../../package.json'))
);
