# generated by Neptune Namespaces v3.x.x
# file: tests/Art.Events/namespace.coffee

module.exports = (require '../namespace').addNamespace 'Art.Events', class Events extends Neptune.PackageNamespace
  @version: require('../../../package.json').version
