// Generated by CoffeeScript 1.12.7
(function() {
  var Core, MinimalBaseObject,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  MinimalBaseObject = require('../../MinimalBaseObject');

  module.exports = Core = (function(superClass) {
    extend(Core, superClass);

    function Core(value) {
      Core.__super__.constructor.apply(this, arguments);
      this.value = value;
      if (value && value.constructor.name === "HTMLImageElement") {
        this.image = value;
      }
    }

    Core.getter({
      children: function() {
        return null;
      }
    });

    Core.prototype.toString = function() {
      return "" + this.value;
    };

    return Core;

  })(MinimalBaseObject);

}).call(this);

//# sourceMappingURL=Core.js.map
