# generated by Neptune Namespaces v3.x.x
# file: Art.StandardLib/Inspect/Inspected/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  Array:  require './Array'
  Core:   require './Core'
  Object: require './Object'
  String: require './String'