# generated by Neptune Namespaces v3.x.x
# file: Art.StandardLib/Inspect/Inspected/namespace.coffee

module.exports = (require '../namespace').addNamespace('Inspected', class Inspected extends Neptune.PackageNamespace)
