// generated by Neptune Namespaces v4.x.x
// file: Art.StandardLib/Inspect/Inspected/namespace.js

module.exports = require('../namespace').addNamespace(
  'Inspected',
  class Inspected extends Neptune.PackageNamespace {}
);
