# generated by Neptune Namespaces v1.x.x
# file: Art/StandardLib/Core/namespace.coffee

StandardLib = require '../namespace'
module.exports = StandardLib.Core ||
StandardLib.addNamespace 'Core', class Core extends Neptune.Base
  ;