// Generated by CoffeeScript 1.12.7
(function() {
  var PackageNamespace,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  module.exports = PackageNamespace = (function(superClass) {
    extend(PackageNamespace, superClass);

    function PackageNamespace() {
      return PackageNamespace.__super__.constructor.apply(this, arguments);
    }

    PackageNamespace._configureNamespace = function(arg) {
      this.version = arg.version;
      return this;
    };

    return PackageNamespace;

  })(require('./NamespaceClass'));

}).call(this);
