// generated by Neptune Namespaces v4.x.x
// file: test/index.js

(module.exports = require('./namespace'))

.addModules({
  AceMainTest:       require('./AceMain.test'),
  LoadAceConfigTest: require('./LoadAceConfig.test'),
  StandardImport:    require('./StandardImport')
});