// generated by Neptune Namespaces v4.x.x
// file: tests/art/foundation/tools/index.js

(module.exports = require('./namespace'))

.addModules({
  BatchLoader:             require('./batch_loader'),
  JsonStore:               require('./json_store'),
  ProgressAdapter:         require('./ProgressAdapter'),
  Stat:                    require('./stat'),
  Transaction:             require('./transaction'),
  WebWorker:               require('./web_worker'),
  WorkerForWorkerRpcTests: require('./worker_for_worker_rpc_tests'),
  WorkerRpc:               require('./worker_rpc')
});