// generated by Neptune Namespaces v4.x.x
// file: tests/art/foundation/tools/namespace.js

module.exports = require('../namespace').addNamespace(
  'Tools',
  class Tools extends Neptune.PackageNamespace {}
);
