ArtStandardLib = require 'art-standard-lib'
module.exports = ArtStandardLib.merge ArtStandardLib,
  require '../index'
  test: (args...) -> global.test args...
  setup: (args...) -> global.setup args...
  teardown: (args...) -> global.teardown args...
