import { createRequire } from 'module';
const require = createRequire(import.meta.url);

const {
  Html, Head, Body,
  Base, BaseFont, Link, Meta, Script, Style, Title,
  Address, Article, Aside, Center, Footer, Header,
  H1, H2, H3, H4, H5, H6,
  Main, Nav, Section,
  BlockQuote, Dd, Dir, Div, Dl, Dt,
  FigCaption, Figure, Hr, Li, Menu, MenuItem,
  Ol, P, Pre, Ul,
  A, Abbr, Acronym, B, Bdi, Bdo, Big, Br,
  Cite, Code, Del, Dfn, Em, Font, I, Ins,
  Kbd, Mark, Q, Rp, Rt, Ruby, S, Samp,
  Small, Span, Strike, Strong, Sub, Sup,
  Time, Tt, U, Var, Wbr,
  Area, Audio, Canvas, Embed, IFrame, Img,
  Map, ObjectElement, Param, Source, Track, Video,
  Applet, Frame, FrameSet, NoFrames,
  NoScript,
  Caption, Col, ColGroup, Table, TBody,
  Td, TFoot, Th, THead, Tr,
  Button, DataList, FieldSet, Form, Input,
  KeyGen, Label, Legend, Meter, OptGroup,
  Option, Output, Progress, Select, TextArea,
  Textarea,
  Details, Dialog, Summary,
  RawHtml
} = require('./build/index.js');

export {
  Html, Head, Body,
  Base, BaseFont, Link, Meta, Script, Style, Title,
  Address, Article, Aside, Center, Footer, Header,
  H1, H2, H3, H4, H5, H6,
  Main, Nav, Section,
  BlockQuote, Dd, Dir, Div, Dl, Dt,
  FigCaption, Figure, Hr, Li, Menu, MenuItem,
  Ol, P, Pre, Ul,
  A, Abbr, Acronym, B, Bdi, Bdo, Big, Br,
  Cite, Code, Del, Dfn, Em, Font, I, Ins,
  Kbd, Mark, Q, Rp, Rt, Ruby, S, Samp,
  Small, Span, Strike, Strong, Sub, Sup,
  Time, Tt, U, Var, Wbr,
  Area, Audio, Canvas, Embed, IFrame, Img,
  Map, ObjectElement, Param, Source, Track, Video,
  Applet, Frame, FrameSet, NoFrames,
  NoScript,
  Caption, Col, ColGroup, Table, TBody,
  Td, TFoot, Th, THead, Tr,
  Button, DataList, FieldSet, Form, Input,
  KeyGen, Label, Legend, Meter, OptGroup,
  Option, Output, Progress, Select, TextArea,
  Textarea,
  Details, Dialog, Summary,
  RawHtml
};

export default {
  Html, Head, Body,
  Base, BaseFont, Link, Meta, Script, Style, Title,
  Address, Article, Aside, Center, Footer, Header,
  H1, H2, H3, H4, H5, H6,
  Main, Nav, Section,
  BlockQuote, Dd, Dir, Div, Dl, Dt,
  FigCaption, Figure, Hr, Li, Menu, MenuItem,
  Ol, P, Pre, Ul,
  A, Abbr, Acronym, B, Bdi, Bdo, Big, Br,
  Cite, Code, Del, Dfn, Em, Font, I, Ins,
  Kbd, Mark, Q, Rp, Rt, Ruby, S, Samp,
  Small, Span, Strike, Strong, Sub, Sup,
  Time, Tt, U, Var, Wbr,
  Area, Audio, Canvas, Embed, IFrame, Img,
  Map, ObjectElement, Param, Source, Track, Video,
  Applet, Frame, FrameSet, NoFrames,
  NoScript,
  Caption, Col, ColGroup, Table, TBody,
  Td, TFoot, Th, THead, Tr,
  Button, DataList, FieldSet, Form, Input,
  KeyGen, Label, Legend, Meter, OptGroup,
  Option, Output, Progress, Select, TextArea,
  Textarea,
  Details, Dialog, Summary,
  RawHtml
};