# generated by Neptune Namespaces v3.x.x
# file: tests/Art.EmailValidator/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  FindEmailDomain: require './findEmailDomain'
  GetDomain:       require './getDomain'      
  ValidateEmail:   require './validateEmail'  