// generated by Neptune Namespaces v4.x.x
// file: tests/Art.EmailValidator/index.js

(module.exports = require('./namespace'))

.addModules({
  FindEmailDomain: require('./findEmailDomain'),
  GetDomain:       require('./getDomain'),
  ValidateEmail:   require('./validateEmail')
});