// generated by Neptune Namespaces v4.x.x
// file: tests/Art.EmailValidator/namespace.js

module.exports = require('../namespace').addNamespace(
  'Art.EmailValidator',
  (class EmailValidator extends Neptune.PackageNamespace {})
  ._configureNamespace(require('../../../package.json'))
);
