# generated by Neptune Namespaces v3.x.x
# file: tests/Art.EmailValidator/namespace.coffee

module.exports = (require '../namespace').addNamespace 'Art.EmailValidator', class EmailValidator extends Neptune.PackageNamespace
  @version: require('../../../package.json').version
