# generated by Neptune Namespaces v1.x.x
# file: tests/Art/ClassSystem/BaseClass/index.coffee

module.exports = require './namespace'
.addModules
  Basic:              require './Basic'             
  ExtendedProperties: require './ExtendedProperties'