# generated by Neptune Namespaces v1.x.x
# file: tests/Art/ClassSystem/BaseClass/namespace.coffee

ClassSystem = require '../namespace'
module.exports = ClassSystem.BaseClass ||
ClassSystem.addNamespace 'BaseClass', class BaseClass extends Neptune.Base
  ;