# generated by Neptune Namespaces v1.x.x
# file: Art/RestClient/namespace.coffee

Art = require '../namespace'
module.exports = Art.RestClient ||
Art.addNamespace 'RestClient', class RestClient extends Neptune.Base
  ;