// generated by Neptune Namespaces v4.x.x
// file: tests/Art.StandardLib/index.js

(module.exports = require('./namespace'))

.addModules({
  Array:                        require('./array'),
  ArrayCompactFlatten:          require('./ArrayCompactFlatten'),
  ArrayCompactFlattenNonStrict: require('./ArrayCompactFlattenNonStrict'),
  ArrayExtensions:              require('./ArrayExtensions'),
  Async:                        require('./Async'),
  CallStack:                    require('./CallStack'),
  Clone:                        require('./clone'),
  DateExtensions:               require('./DateExtensions'),
  Environment:                  require('./Environment'),
  Eq:                           require('./eq'),
  Iteration:                    require('./Iteration'),
  Map:                          require('./Map'),
  Math:                         require('./math'),
  NextTick:                     require('./nextTick'),
  ObjectDiff:                   require('./object_diff'),
  ObjectExtensions:             require('./ObjectExtensions'),
  ParseUrl:                     require('./parse_url'),
  PlainData:                    require('./plain_data'),
  Promise:                      require('./promise'),
  PromiseWorkerPool:            require('./PromiseWorkerPool'),
  RegExpExtensions:             require('./RegExpExtensions'),
  RequestError:                 require('./RequestError'),
  ReschedulableTimer:           require('./ReschedulableTimer'),
  Ruby:                         require('./ruby'),
  StandardImport:               require('./StandardImport'),
  StringCase:                   require('./string_case'),
  StringExtensions:             require('./StringExtensions'),
  Time:                         require('./time'),
  Types:                        require('./types'),
  Unique:                       require('./unique')
});
require('./Core');
require('./Inspect');