// generated by Neptune Namespaces v4.x.x
// file: test/tests/Art.StandardLib/namespace.js

module.exports = require('../namespace').addNamespace(
  'Art.StandardLib',
  class StandardLib extends Neptune.PackageNamespace {}
);
