{version} = require '../../package.json'
{upperCamelCase, fileWithoutExtension, peek, arrayWithoutLast} = require './MiniFoundation'

module.exports = class Helper
  @generatedByString:         "# generated by Neptune Namespaces v#{version[0]}.x.x"
  @globalNamespaceName:       "Neptune"
  @neptuneBaseClass:          "#{@globalNamespaceName}.Base"
  @shouldIgnore:              (itemName) -> !!itemName.match /^(\..*|index.coffee|namespace.coffee)$/
  @shouldNotNamespace:        (itemName) -> !!itemName.match /^-/
  @shouldIncludeInNamespace:  (file, namespaceName) -> toModuleName(file) == namespaceName
  @toFilename:                (path) -> peek path.split('/')
  @toModuleName:              toModuleName = (itemName) -> upperCamelCase fileWithoutExtension itemName
