# generated by Neptune Namespaces v1.x.x
# file: Generation/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  ArrayCompactFlatten: require './ArrayCompactFlatten'
  Generator:           require './Generator'          
  Helper:              require './Helper'             
  MiniFoundation:      require './MiniFoundation'     
  NamespaceStructure:  require './NamespaceStructure' 
require './Generators'