# generated by Neptune Namespaces v2.x.x
# file: Generation/namespace.coffee

module.exports = (require 'neptune-namespaces').addNamespace('Generation', class Generation extends Neptune.Base)
require './Generators/namespace'