# generated by Neptune Namespaces v3.x.x
# file: Generation/namespace.coffee

module.exports = (require 'neptune-namespaces').addNamespace('Generation', class Generation extends Neptune.PackageNamespace)
require './Generators/namespace'