// generated by Neptune Namespaces v4.x.x
// file: Art.Build.Configurator/Recipes/index.js

(module.exports = require('./namespace'))

.addModules({
  App:       require('./App'),
  ClientApp: require('./ClientApp'),
  Core:      require('./Core'),
  DemoApp:   require('./DemoApp'),
  Node:      require('./Node')
});