// generated by Neptune Namespaces v4.x.x
// file: Art.Build.Configurator/Recipes/namespace.js

module.exports = require('../namespace').addNamespace(
  'Recipes',
  class Recipes extends Neptune.PackageNamespace {}
);
