// generated by Neptune Namespaces v4.x.x
// file: perfs/namespace.js

module.exports = require('neptune-namespaces-runtime').addNamespace(
  'Perfs',
  (class Perfs extends Neptune.PackageNamespace {})
  ._configureNamespace(require('../../package.json'))
);
require('./art/namespace');
require('./javascript/namespace');