# generated by Neptune Namespaces v1.x.x
# file: tests/Art/ClassSystem/BaseObject/index.coffee

module.exports = require './namespace'
.addModules
  Basic:              require './basic'             
  ExtendedProperties: require './ExtendedProperties'