// generated by Neptune Namespaces v4.x.x
// file: tests/ArtSuite.Cli/index.js

(module.exports = require('./namespace'))

.addModules({
  Help:  require('./Help'),
  Main:  require('./Main'),
  Parse: require('./Parse')
});