# generated by Neptune Namespaces v1.x.x
# file: Art/BuildConfigurator/index.coffee

module.exports = require './namespace'
.includeInNamespace require './BuildConfigurator'
.addModules
  ConfigurePackageJson: require './ConfigurePackageJson'
  ConfigureWebpack:     require './ConfigureWebpack'    
require './Data'