# generated by Neptune Namespaces v2.x.x
# file: Art/BuildConfigurator/index.coffee

module.exports = require './namespace'
module.exports
.includeInNamespace require './BuildConfigurator'
.addModules
  ConfigurePackageJson: require './ConfigurePackageJson'
  ConfigureWebpack:     require './ConfigureWebpack'    
  DefaultFiles:         require './DefaultFiles'        
  Publish:              require './Publish'             
  StandardImport:       require './StandardImport'      
  Versioning:           require './Versioning'          
require './Data'
require './FileBuilder'