# generated by Neptune Namespaces v1.x.x
# file: Art/BuildConfigurator/namespace.coffee

Art = require '../namespace'
module.exports = Art.BuildConfigurator ||
Art.addNamespace 'BuildConfigurator', class BuildConfigurator extends Neptune.Base
  ;