// generated by Neptune Namespaces v4.x.x
// file: tests/NeptuneNamespaces/namespace.js

module.exports = module.exports =  require('../namespace').vivifySubnamespace('NeptuneNamespaces');
require('./MockedFileSystem/namespace');