# generated by Neptune Namespaces v0.1.0
# file: my_module_directories/my_module_directories/namespace.coffee

MyModuleDirectories = require '../namespace'
module.exports = MyModuleDirectories.MyModuleDirectories ||
MyModuleDirectories.addNamespace class MyModuleDirectories extends Neptune.Base
  ;