# generated by Neptune Namespaces v1.x.x
# file: geometry/shapes/namespace.coffee

Geometry = require '../namespace'
module.exports = Geometry.Shapes ||
Geometry.addNamespace 'Shapes', class Shapes extends Neptune.Base
  ;