# generated by Neptune Namespaces v3.x.x
# file: Art.Browser.Tools/namespace.coffee

module.exports = (require 'neptune-namespaces').addNamespace 'Art.Browser.Tools', class Tools extends Neptune.PackageNamespace
  @version: require('../../package.json').version
