# generated by Neptune Namespaces v3.x.x
# file: tests/Art.RestClient/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  Basics:           require './Basics'          
  NormalizeHeaders: require './NormalizeHeaders'