// generated by Neptune Namespaces v4.x.x
// file: tests/Art.RestClient/index.js

(module.exports = require('./namespace'))

.addModules({
  Basics:           require('./Basics'),
  NormalizeHeaders: require('./NormalizeHeaders')
});