# generated by Neptune Namespaces v3.x.x
# file: tests/Art.RestClient/namespace.coffee

module.exports = (require '../namespace').addNamespace 'Art.RestClient', class RestClient extends Neptune.PackageNamespace
  @version: require('../../../package.json').version
