// generated by Neptune Namespaces v4.x.x
// file: tests/Art.RestClient/namespace.js

module.exports = require('../namespace').addNamespace(
  'Art.RestClient',
  (class RestClient extends Neptune.PackageNamespace {})
  ._configureNamespace(require('../../../package.json'))
);
