// generated by Neptune Namespaces v4.x.x
// file: tests/index.js

(module.exports = require('./namespace'))

.addModules({
  Limits:             require('./Limits'),
  LimitsTest:         require('./Limits.test'),
  PostValidationTest: require('./PostValidation.test'),
  StandardImport:     require('./StandardImport'),
  SubValidationTest:  require('./SubValidation.test'),
  ValidatorTest:      require('./Validator.test')
});