# generated by Neptune Namespaces v3.x.x
# file: tests/Art.Browser.Tools/namespace.coffee

module.exports = (require '../namespace').addNamespace 'Art.Browser.Tools', class Tools extends Neptune.PackageNamespace
  @version: require('../../../package.json').version
