// generated by Neptune Namespaces v4.x.x
// file: perfs/javascript/index.js

(module.exports = require('./namespace'))

.addModules({
  ElementCreationArgumentProcessing: require('./element_creation_argument_processing'),
  GetterSetter:                      require('./getter_setter'),
  Math:                              require('./math'),
  MembersAndLocals:                  require('./members_and_locals'),
  MethodInvocation:                  require('./method_invocation'),
  ObjectsAndArrays:                  require('./objects_and_arrays'),
  ParameterPassing:                  require('./parameter_passing')
});