// generated by Neptune Namespaces v4.x.x
// file: perfs/javascript/namespace.js

module.exports = require('../namespace').addNamespace(
  'Javascript',
  class Javascript extends Neptune.PackageNamespace {}
);
