# generated by Neptune Namespaces v2.x.x
# file: tests/Art/Epoch/namespace.coffee

Art = require '../namespace'
module.exports = Art.Epoch ||
Art.addNamespace 'Epoch', class Epoch extends Neptune.Base
  ;
