// generated by Neptune Namespaces v3.x.x
// file: tests/index.js

(module.exports = require('./namespace'))

.addModules({
  ExtendedMockFs: require('./ExtendedMockFs'),
  StandardImport: require('./StandardImport'),
  Test:           require('./test')
});
require('./Generation');
require('./NeptuneNamespaces');