// generated by Neptune Namespaces v3.x.x
// file: tests/index.js

(module.exports = require('./namespace'))

.addModules({
  StandardImport: require('./StandardImport')
});
require('./Generation');
require('./NeptuneNamespaces');