// generated by Neptune Namespaces v3.x.x
// file: tests/namespace.js

module.exports = require('neptune-namespaces').addNamespace(
  'Tests',
  (class Tests extends Neptune.PackageNamespace {})
  ._configureNamespace(require('../../package.json'))
);
require('./Generation/namespace');
require('./NeptuneNamespaces/namespace');