# generated by Neptune Namespaces v0.5.0
# file: tests/namespace.coffee

Neptune = require 'neptune-namespaces'
module.exports = Neptune.Tests ||
Neptune.addNamespace 'Tests', class Tests extends Neptune.Base
  ;