// generated by Neptune Namespaces v4.x.x
// file: tests/namespace.js

module.exports = module.exports =  require('neptune-namespaces-runtime').vivifySubnamespace('Tests');
require('./art/namespace');