# generated by Neptune Namespaces v2.x.x
# file: tests/Art/ObjectTreeFactory/namespace.coffee

Art = require '../namespace'
module.exports = Art.ObjectTreeFactory ||
Art.addNamespace 'ObjectTreeFactory', class ObjectTreeFactory extends Neptune.Base
  ;
