// generated by Neptune Namespaces v4.x.x
// file: Art.Build.Configurator/index.js

(module.exports = require('./namespace'))
.includeInNamespace(require('./Configurator'))
.addModules({
  Main:                 require('./Main'),
  Publish:              require('./Publish'),
  Recipe:               require('./Recipe'),
  RunNeptuneNamespaces: require('./RunNeptuneNamespaces'),
  StandardImport:       require('./StandardImport'),
  Versioning:           require('./Versioning')
});
require('./Configurators');
require('./Data');
require('./Recipes');