// generated by Neptune Namespaces v4.x.x
// file: Art.Build.Configurator/namespace.js

module.exports = require('neptune-namespaces').addNamespace(
  'Art.Build.Configurator',
  (class Configurator extends Neptune.PackageNamespace {})
  ._configureNamespace(require('../../package.json'))
);
require('./Configurators/namespace');
require('./Data/namespace');
require('./Recipes/namespace');