# generated by Neptune Namespaces v2.x.x
# file: tests/Art/ClassSystem/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  DeclarableMixin:           require './DeclarableMixin'          
  ExtendedablePropertyMixin: require './ExtendedablePropertyMixin'
require './BaseClass'