# generated by Neptune Namespaces v2.x.x
# file: tests/Art/ClassSystem/namespace.coffee

Art = require '../namespace'
module.exports = Art.ClassSystem ||
Art.addNamespace 'ClassSystem', class ClassSystem extends Neptune.Base
  ;
require './BaseClass/namespace'