# generated by Neptune Namespaces v1.x.x
# file: Art/ClassSystem/index.coffee

module.exports = require './namespace'
.includeInNamespace require './ClassSystem'
.addModules
  BaseClass:        require './BaseClass'       
  BaseObject:       require './BaseObject'      
  WebpackHotLoader: require './WebpackHotLoader'