# generated by Neptune Namespaces v3.x.x
# file: Art/ClassSystem/namespace.coffee

module.exports = (require '../namespace').addNamespace 'ClassSystem', class ClassSystem extends Neptune.PackageNamespace
  @version: require('../../../package.json').version
