// generated by Neptune Namespaces v4.x.x
// file: Art/EpochedState/namespace.js

module.exports = require('../namespace').addNamespace(
  'EpochedState',
  (class EpochedState extends Neptune.PackageNamespace {})
  ._configureNamespace(require('../../../package.json'))
);
