// Generated by CoffeeScript 1.12.7
(function() {
  var BaseObject,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  module.exports = BaseObject = (function(superClass) {
    extend(BaseObject, superClass);

    function BaseObject() {
      return BaseObject.__super__.constructor.apply(this, arguments);
    }

    return BaseObject;

  })(require("./BaseClass"));

}).call(this);

//# sourceMappingURL=BaseObject.js.map
