# generated by Neptune Namespaces v2.x.x
# file: tests/Art/RestClient/namespace.coffee

Art = require '../namespace'
module.exports = Art.RestClient ||
Art.addNamespace 'RestClient', class RestClient extends Neptune.Base
  ;
