// generated by Neptune Namespaces v4.x.x
// file: tests/Art/namespace.js

module.exports = module.exports =  require('../namespace').vivifySubnamespace('Art');
require('./BuildConfigurator/namespace');