# generated by Neptune Namespaces v0.1.0
# file: my_module_directories/normal_name/namespace.coffee

MyModuleDirectories = require '../namespace'
module.exports = MyModuleDirectories.NormalName ||
MyModuleDirectories.addNamespace class NormalName extends Neptune.Base
  ;