# generated by Neptune Namespaces v1.x.x
# file: NeptuneLib/index.coffee

module.exports = require './namespace'
.includeInNamespace require './NeptuneLib'
.addModules
  ArrayCompactFlatten: require './ArrayCompactFlatten'
  Merge:               require './Merge'              
  StringCase:          require './StringCase'         
  Types:               require './Types'              