# generated by Neptune Namespaces v1.x.x
# file: NeptuneLib/namespace.coffee

Neptune = require 'neptune-namespaces'
module.exports = Neptune.NeptuneLib ||
Neptune.addNamespace 'NeptuneLib', class NeptuneLib extends Neptune.Base
  ;