// generated by Neptune Namespaces v4.x.x
// file: tests/Art.StandardLib/Inspect/index.js

(module.exports = require('./namespace'))

.addModules({
  FormattedInspect:   require('./formatted_inspect'),
  Inspected:          require('./inspected'),
  Inspector2:         require('./inspector2'),
  Main:               require('./main'),
  StandardImport:     require('./StandardImport'),
  ToInspectedObjects: require('./to_inspected_objects')
});