// generated by Neptune Namespaces v4.x.x
// file: tests/Art.StandardLib/Inspect/namespace.js

module.exports = require('../namespace').addNamespace(
  'Inspect',
  class Inspect extends Neptune.PackageNamespace {}
);
