# generated by Neptune Namespaces v3.x.x
# file: tests/Art.StandardLib/Inspect/namespace.coffee

module.exports = (require '../namespace').addNamespace('Inspect', class Inspect extends Neptune.PackageNamespace)
