# generated by Neptune Namespaces v0.4.4
# file: Generation/index.coffee

(module.exports = require './namespace')
.addModules
  ArrayCompactFlatten: require './ArrayCompactFlatten'
  Generator: require './Generator'
  Helper: require './Helper'
  MiniFoundation: require './MiniFoundation'
  NamespaceStructure: require './NamespaceStructure'
  Generators: require './Generators'