# generated by Neptune Namespaces v0.x.x
# file: Generation/namespace.coffee

Neptune = require 'neptune-namespaces'
module.exports = Neptune.Generation ||
Neptune.addNamespace 'Generation', class Generation extends Neptune.Base
  ;