// generated by Neptune Namespaces v4.x.x
// file: tests/art/dev_tools/namespace.js

module.exports = require('../namespace').addNamespace(
  'DevTools',
  class DevTools extends Neptune.PackageNamespace {}
);
