# generated by Neptune Namespaces v3.x.x
# file: tests/Art.ClassSystem/BaseClass/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  Basic:      require './Basic'     
  PostCreate: require './PostCreate'