// generated by Neptune Namespaces v4.x.x
// file: tests/Art.ClassSystem/BaseClass/index.js

(module.exports = require('./namespace'))

.addModules({
  Basic:      require('./Basic'),
  PostCreate: require('./PostCreate')
});