// generated by Neptune Namespaces v4.x.x
// file: tests/Art.ClassSystem/BaseClass/namespace.js

module.exports = require('../namespace').addNamespace(
  'BaseClass',
  class BaseClass extends Neptune.PackageNamespace {}
);
