# generated by Neptune Namespaces v3.x.x
# file: tests/Art.ClassSystem/BaseClass/namespace.coffee

module.exports = (require '../namespace').addNamespace('BaseClass', class BaseClass extends Neptune.PackageNamespace)
