# generated by Neptune Namespaces v3.x.x
# file: Art.BrowserTools/index.coffee

module.exports = require './namespace'
module.exports
.includeInNamespace require './BrowserTools'
.addModules
  BrowserDetection:        require './BrowserDetection'       
  Cookie:                  require './Cookie'                 
  Dom:                     require './Dom'                    
  DomElementFactories:     require './DomElementFactories'    
  Download:                require './Download'               
  EmailBrowserTools:       require './EmailBrowserTools'      
  File:                    require './File'                   
  IPhoneDeviceInformation: require './iPhoneDeviceInformation'
  StandardImport:          require './StandardImport'         
  UriBrowserTools:         require './UriBrowserTools'        
  UseragentRegExp:         require './UseragentRegExp'        