# generated by Neptune Namespaces v3.x.x
# file: Art.BrowserTools/index.coffee

module.exports = require './namespace'
module.exports
.includeInNamespace require './BrowserTools'
.addModules
  Cookie:              require './Cookie'             
  Dom:                 require './Dom'                
  DomElementFactories: require './DomElementFactories'
  Download:            require './Download'           
  File:                require './File'               
  StandardImport:      require './StandardImport'     