# generated by Neptune Namespaces v3.x.x
# file: Art.BrowserTools/namespace.coffee

module.exports = (require 'neptune-namespaces').addNamespace 'Art.BrowserTools', class BrowserTools extends Neptune.PackageNamespace
  @version: require('../../package.json').version
