// generated by Neptune Namespaces v4.x.x
// file: Art.BrowserTools/namespace.js

module.exports = require('neptune-namespaces').addNamespace(
  'Art.BrowserTools',
  (class BrowserTools extends Neptune.PackageNamespace {})
  ._configureNamespace(require('../../package.json'))
);
