// generated by Neptune Namespaces v4.x.x
// file: Art.Foundation/.DevTools/namespace.js

module.exports = require('../namespace').addNamespace(
  'DevTools',
  class DevTools extends Neptune.PackageNamespace {}
);
require('./DomConsole/namespace');
require('./Webpack/namespace');