# generated by Neptune Namespaces v2.x.x
# file: tests/Art/StandardLib/Inspect/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  FormattedInspect:   require './formatted_inspect'   
  Inspected:          require './inspected'           
  Inspector2:         require './inspector2'          
  Main:               require './main'                
  ToInspectedObjects: require './to_inspected_objects'