# generated by Neptune Namespaces v1.x.x
# file: tests/Art/StandardLib/Inspect/namespace.coffee

StandardLib = require '../namespace'
module.exports = StandardLib.Inspect ||
StandardLib.addNamespace 'Inspect', class Inspect extends Neptune.Base
  ;