// generated by Neptune Namespaces v3.x.x
// file: NeptuneNamespaces/index.js

(module.exports = require('./namespace'))

.addModules({
  ArrayCompactFlatten: require('./ArrayCompactFlatten'),
  Generator:           require('./Generator'),
  Helper:              require('./Helper'),
  MiniFoundation:      require('./MiniFoundation'),
  NamespaceStructure:  require('./NamespaceStructure'),
  PackageRoot:         require('./PackageRoot'),
  StandardImport:      require('./StandardImport')
});
require('./Generators');