# generated by Neptune Namespaces v3.x.x
# file: NeptuneNamespaces/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  ArrayCompactFlatten: require './ArrayCompactFlatten'
  Generator:           require './Generator'          
  GeneratorOld:        require './GeneratorOld'       
  Helper:              require './Helper'             
  MiniFoundation:      require './MiniFoundation'     
  NamespaceStructure:  require './NamespaceStructure' 
  PackageRoot:         require './PackageRoot'        
  StandardImport:      require './StandardImport'     
require './Generators'