// generated by Neptune Namespaces v4.x.x
// file: NeptuneNamespaces/namespace.js

module.exports = require('neptune-namespaces-runtime').addNamespace(
  'NeptuneNamespaces',
  (class NeptuneNamespaces extends Neptune.PackageNamespace {})
  ._configureNamespace(require('../../package.json'))
);
require('./Generators/namespace');