// generated by Neptune Namespaces v3.x.x
// file: NeptuneNamespaces/namespace.js

module.exports = require('neptune-namespaces').addNamespace(
  'NeptuneNamespaces',
  (class NeptuneNamespaces extends Neptune.PackageNamespace {})
  ._configureNamespace(require('../../package.json'))
);
require('./Generators/namespace');