# generated by Neptune Namespaces v3.x.x
# file: NeptuneNamespaces/namespace.coffee

module.exports = (require 'neptune-namespaces').addNamespace 'NeptuneNamespaces', class NeptuneNamespaces extends Neptune.PackageNamespace
  @version: require('../../package.json').version
require './Generators/namespace'