# generated by Neptune Namespaces v3.x.x
# file: tests/NeptuneNamespaces/MockedFileSystem/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  Genrator: require './Genrator'