# generated by Neptune Namespaces v3.x.x
# file: tests/NeptuneNamespaces/MockedFileSystem/namespace.coffee

module.exports = (require '../namespace').addNamespace('MockedFileSystem', class MockedFileSystem extends Neptune.PackageNamespace)
