// generated by Neptune Namespaces v4.x.x
// file: tests/NeptuneNamespaces/MockedFileSystem/namespace.js

module.exports = require('../namespace').addNamespace(
  'MockedFileSystem',
  class MockedFileSystem extends Neptune.PackageNamespace {}
);
