# generated by Neptune Namespaces v0.1.0
# file: my_module_with_both/normal_directory/namespace.coffee

MyModuleWithBoth = require '../namespace'
module.exports = MyModuleWithBoth.NormalDirectory ||
MyModuleWithBoth.addNamespace class NormalDirectory extends Neptune.Base
  ;