# generated by Neptune Namespaces v0.1.0
# file: my_module/index.coffee

require './-required_but_not_added'
(module.exports = require './namespace')
.includeInNamespace(require './my_module')
.addModules
  RequireFirst:        require './___require_first'
  RequireSecond:       require './__require_second'
  RequireThird:        require './_require_third'
  NormalFilename:      require './normal_filename'