# generated by Neptune Namespaces v0.1.0
# file: my_module/namespace.coffee

require 'neptune-namespaces'
module.exports = Neptune.MyModule ||
Neptune.addNamespace class MyModule extends Neptune.Base
  ;