// generated by Neptune Namespaces v4.x.x
// file: tests/art/foundation/namespace.js

module.exports = require('../namespace').addNamespace(
  'Foundation',
  class Foundation extends Neptune.PackageNamespace {}
);
require('./browser/namespace');
require('./tools/namespace');