// generated by Neptune Namespaces v4.x.x
// file: tests/ArtSuite.Cli/namespace.js

module.exports = require('../namespace').addNamespace(
  'ArtSuite.Cli',
  (class Cli extends Neptune.PackageNamespace {})
  ._configureNamespace(require('../../../package.json'))
);
