# generated by Neptune Namespaces v3.x.x
# file: tests/Art/Config/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  ConfigRegistry:   require './ConfigRegistry'  
  TestConfig:       require './TestConfig'      
  TestConfigurable: require './TestConfigurable'