# generated by Neptune Namespaces v3.x.x
# file: tests/Art/Config/namespace.coffee

module.exports = (require '../namespace').addNamespace 'Config', class Config extends Neptune.PackageNamespace
  @version: require('../../../../package.json').version
