# generated by Neptune Namespaces v2.x.x
# file: tests/Art/Config/namespace.coffee

Art = require '../namespace'
module.exports = Art.Config ||
Art.addNamespace 'Config', class Config extends Neptune.Base
  ;
