# generated by Neptune Namespaces v0.5.0
# file: Generation/Generators/index.coffee

module.exports = require './namespace'
.addModules
  IndexGenerator:     require './IndexGenerator'    
  NamespaceGenerator: require './NamespaceGenerator'