# generated by Neptune Namespaces v0.4.4
# file: Generation/Generators/index.coffee

(module.exports = require './namespace')
.addModules
  IndexGenerator: require './IndexGenerator'
  NamespaceGenerator: require './NamespaceGenerator'