# generated by Neptune Namespaces v0.4.4
# file: Generation/Generators/namespace.coffee

Generation = require '../namespace'
module.exports = Generation.Generators ||
Generation.addNamespace 'Generators', class Generators extends Neptune.Base
  ;