# generated by Neptune Namespaces v3.x.x
# file: Art.StandardLib/Core/index.coffee

module.exports = require './namespace'
module.exports
.includeInNamespace require './Core'
.addModules
  ArrayCompactFlatten: require './ArrayCompactFlatten'
  Merge:               require './Merge'
  StringCase:          require './StringCase'
  Types:               require './Types'