// generated by Neptune Namespaces v3.x.x
// file: Art.StandardLib/Core/index.js

(module.exports = require('./namespace'))
.includeInNamespace(require('./Core'))
.addModules({
  ArrayCompactFlatten: require('./ArrayCompactFlatten'),
  Merge:               require('./Merge'),
  StringCase:          require('./StringCase'),
  Types:               require('./Types')
});