// generated by Neptune Namespaces v3.x.x
// file: Art.StandardLib/Core/namespace.js

module.exports = require('../namespace').addNamespace(
  'Core',
  class Core extends Neptune.PackageNamespace {}
);
