# generated by Neptune Namespaces v2.x.x
# file: Art/StandardLib/Inspect/namespace.coffee

StandardLib = require '../namespace'
module.exports = StandardLib.Inspect ||
StandardLib.addNamespace 'Inspect', class Inspect extends Neptune.Base
  ;
require './Inspected/namespace'