# generated by Neptune Namespaces v3.x.x
# file: Art.Xbd/index.coffee

module.exports = require './namespace'
module.exports
.includeInNamespace require './Xbd'
.addModules
  XbdDictionary: require './XbdDictionary'
  XbdTag:        require './XbdTag'       