# generated by Neptune Namespaces v3.x.x
# file: Art.Xbd/namespace.coffee

module.exports = (require 'neptune-namespaces').addNamespace 'Art.Xbd', class Xbd extends Neptune.PackageNamespace
  @version: require('../../package.json').version
