// Generated by CoffeeScript 1.12.7
(function() {
  var defaultArtConfigName;

  module.exports = [
    {
      Config: require('./Configuration'),
      config: {
        yesArtConfig: true
      },
      configName: defaultArtConfigName = "Development",
      defaultArtConfigName: defaultArtConfigName
    }, require('./Main')
  ];

}).call(this);
