// generated by Neptune Namespaces v4.x.x
// file: Art.Config/index.js

(module.exports = require('./namespace'))
.includeInNamespace(require('./Config'))
.addModules({
  ConfigRegistry: require('./ConfigRegistry'),
  Configurable:   require('./Configurable'),
  Configuration:  require('./Configuration'),
  Configure:      require('./Configure'),
  Lib:            require('./Lib'),
  PublicLib:      require('./PublicLib')
});