// generated by Neptune Namespaces v4.x.x
// file: Art.Config/namespace.js

module.exports = require('neptune-namespaces').addNamespace(
  'Art.Config',
  (class Config extends Neptune.PackageNamespace {})
  ._configureNamespace(require('../../package.json'))
);
