# generated by Neptune Namespaces v3.x.x
# file: Art.Config/namespace.coffee

module.exports = (require 'neptune-namespaces').addNamespace 'Art.Config', class Config extends Neptune.PackageNamespace
  @version: require('../../package.json').version
